name: Habemus PHP Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:    
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        # windows-latest, macOS-latest?
        operating-system: [ubuntu-latest]
        php-versions: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1']
        coverage: [xdebug]
        coverage-driver:
          - "pcov"
          - "xdebug"
          - "xdebug3"

        exclude:
          - php-version: "8.0"
            coverage-driver: "xdebug"
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Check PHP Version
      run: php -v 
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Run test suite
      run: composer run-script test
      
    - name: "Run tests with phpunit/phpunit"
      run: "vendor/bin/phpunit --coverage-clover=coverage.xml"

    - name: "Send code coverage report to Codecov.io"
      env:
        CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
      run: "bash <(curl -s https://codecov.io/bash) || true"
